<a href="https://colab.research.google.com/github/Ozgun92/Machine-Learning/blob/main/Data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# the 'as ...' refers to the abbreviated versions that can be used in code.

## Importing the dataset

In [3]:

dataset = pd.read_csv('Data.csv') 

# we use the pandas (abbreviated 'pd') library in order to 
# import the dataset and store it in the variable 'dataset'

X = dataset.iloc[:, :-1].values 

# take all the rows and columns of the table except the last column
# (and all of its corresponding rows). This data is stored in X, which is our matrix of features
# (which we use to predict y).

y = dataset.iloc[:, -1].values

# y depicts our dependent variable (which we want to predict). -1 takes the last column
# of the table and assigns all of its values to y.

In [4]:
print(X)

# this is our matrix of features

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [5]:
print(y)

# these is our dependent variable vector

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [6]:
from sklearn.impute import SimpleImputer

# our table has missing data. In order to deal with that problem, there are multiple approaches we can
# follow. We decide to take the average value of a specific feature, and to impute this average value
# there where a value is missing. For this, we need the Class 'SimpleImputer', which can be found in the
# Scikit - Library, under the module 'impute'.

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# We are creating an instance of the SimpleImputer class. Between the parantheses, we have to input our arguments.
# There arguments can look very different: Instead of the mean value, we could instead impute the median value,
# or the most frequent value etc. We decide for the mean value.
# The first argument 'missing_values=np.nan' just refers to missing values that we want to impute. The second
# argument 'strategy='mean'', refers to the average value we want to impute, in those cells that have missing values.

imputer.fit(X[:, 1:3])

# the 'fit' method will look at our feature columns 1 + 2 (3 is excluded) and calculate the average for those columns.

X[:, 1:3] = imputer.transform(X[:, 1:3])

# in order to replace the missing rows with the average values, we have to call the method 'transform'.

In [7]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# we have another problem: We want to use the first column, which is the country column, as well in order to make
# better predictions. The first column refers to the countries our customers are from. In order to encode this
# column into data that we can use, we need two classes from the scikit-learn library:
# ColumnTransformer and OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

# the class 'ColumnTransformer' takes in two arguments: The first ('transformers') specifies which kind of transformation should,
# occur. The second argument ('remainder') specifies the columns which have to be omitted by the encoding
# which are in our case the second and the third column
# The transformers argument takes in three sub-arguments: 1. What kind of transformation? 2. What kind of encoding?
# 3. The index of the column we want to encode (which is the country column in our case)

X = np.array(ct.fit_transform(X))

# we do 2 things at once: We fit our matrix of features and we transform it. But since the fit_transform method
# needs to be in a numpy array, we wrap it around np.array(). This new matrix of features, we assign to X
# and so, update our matrix of features into one which is OneHotEncoded.

In [9]:
print(X)

# Our new, OneHotEncoded matrix of features

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

# Here, we encoded our dependent variable (yes/no, what we want to predict) into 0 = no, and 1 = yes.
# we fit_transformed this column and updated our dependent variable vector accordingly (by variable assignment)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

# we are splitting our training data in two sets: The training and the test set. 
# We train our model with our training set and use this trained model to make predictions on the test set.
# The test set illustrates new data that haven't been seen by the model before. 
# the test_size argument speficies what percentage of the training data is allocated to the test set.
# the random_state = 1 assures that we will always get the same data for the training and the test set, since
# there is randomness involved in which data is allocated to the training and the test set.

In [ ]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler

# The StandardScaler Class conducts Standardisation (there is also normalization which can be used).

sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

# we use feature scaling in order to get all of the values on a similar scale and thus 
# prevent specific values dominating others. For instance, if we have a column with an average value of 1000
# while we have another that has an average value of 10, the column with the much lower value will be dominated
# so much, that it'll be insignificant for the machine learning model, meaning it won't contribute much to 
# the predicitions.

In [ ]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
